openapi: 3.0.0
info:
  title: API para consultar Movimientos
  description: Servicio encargado de devolver los movimientos de cuentas de depósitos
  contact:
    email: jsburban@bancolombia.com.co
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
paths:
  /cuentas/transacciones/lista-de-movimientos:
    post:
      tags:
      - Movimientos de Cuenta
      summary: searches inventory
      description: |
        Permite obtener los movimientos de una cuenta de depósitos específica
      operationId: POST_listarMovimientos
      parameters:
      - name: message-id
        in: header
        description: Identificador de transacción. Se recomienda usar un UUID para el valor de este campo.
        schema:
          type: string
          maximum: 128
        required: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Movimiento'
      responses:
        '200':
          content:
            application/json:
                schema:
                  $ref: '#/components/schemas/Movimiento'
          description: Respuesta exitosa.
        "400":
          description: Parametros erroneos.
        "500":
          description: Error del servidor.
    head:
      responses:
        '200':
          description: 200 OK
components:
  schemas:
    Movimiento:
      required:
      - movimientoId
      - fecha
      - oficina
      - descripcion
      - referencia
      - monto
      - tipo
      properties:
        fecha:
          type: string
          format: date
          description: 'Fecha efectiva en la cual se hace la afectación del saldo de la cuenta, puede ser de días anteriores.'
          example: '2020-09-15'
        transactionDate:
          type: string
          format: date
          description: 'Fecha de vinculación y aplicación de las transacciones en la cuenta.'
          example: '2020-09-15'
        movimientoId:
          type: string
          description: Código de identificación del movimiento.
          example: '8316'
          maxLength: 6
          minLength: 1
        descripcion:
          type: string
          description: Descripción o nombre del movimiento.
          example: Abono preautorizado donación
          maxLength: 50
        oficina:
            $ref: '#/components/schemas/Oficina'
        referencia:
          type: string
          description: 'Texto en el cual puede indicar una referencia o valor útil para el cliente. Ejemplo: número de documento de identidad, código de una factura.'
          example: '1098912344'
          maxLength: 50
        monto:
          type: number
          format: float
          description: Valor del movimiento.
          maxLength: 21
          minLength: 1
          example: 100000
        tipo:
          type: string
          description: Indica el tipo de movimiento.
          example: DEBITO
          enum:
            - DEBITO
            - CREDITO
    Oficina:
      required:
        - oficinaId
        - nombre
      properties:
        movimientoId:
          type: string
          description: Código de identificación del movimiento.
          example: '8316'
          maxLength: 6
          minLength: 1
        nombre:
          type: string
          description: Nombre de la oficina.
          example: Cajero 1011 Unicentro Pasto
          maxLength: 50